const C=Sweforms,$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={version:1,tasks:[],history:[]},view='dashboard',completeId,storageBlocked=false,installPrompt;
try{const saved=localStorage.getItem(C.KEY);if(saved){const parsed=JSON.parse(saved);if(!C.validateState(parsed))throw Error();state=parsed}}catch{storageBlocked=true}
const fmt=s=>s?new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(s+'T12:00:00')):'No next due date';
const money=n=>new Intl.NumberFormat('en',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,4500)}
function save(next){if(storageBlocked){toast('Saved data could not be read. Restore a backup in Guide & backup.');return false}try{localStorage.setItem(C.KEY,JSON.stringify(next));state=next;render();return true}catch{toast('Could not save. Check your browser storage and create a backup.');return false}}
function transaction(fn){const next=structuredClone(state);fn(next);return save(next)}
function render(){const now=C.today(),limit=C.advance(now,30,'days');$('#overdue').textContent=state.tasks.filter(t=>t.next&&t.next<now).length;$('#soon').textContent=state.tasks.filter(t=>t.next&&t.next>=now&&t.next<=limit).length;$('#done').textContent=state.history.filter(h=>h.date.startsWith(now.slice(0,4))).length;document.querySelectorAll('nav button').forEach(b=>{b.removeAttribute('aria-current');if(b.dataset.view===view)b.setAttribute('aria-current','page')});const content=$('#content');
if(view==='help'){content.innerHTML=`<article class="help"><h2>Your home maintenance, step by step</h2><ol><li>Add your own task or choose from the starter list.</li><li>Set a next due date and an interval for recurring maintenance.</li><li>Select Done when the work is complete. Enter the date and actual cost. Recurring tasks automatically receive a new due date.</li></ol><h3>Add the app to your home screen</h3><p>iPhone/iPad: open the address in Safari, select Share and Add to Home Screen. Android: open in Chrome and select Install app or Add to Home screen from the menu. On a computer, an install button may appear in the address bar. Menu names may vary.</p><h3>Your data and backups</h3><p>Everything is saved locally on this device, in this browser. No account or cloud sync. Clearing website data, private browsing or changing the app address may cause data loss. On some devices, the home screen app has separate storage; import your backup there.</p><p>After your first visit, the app works offline. It does not send reminders while closed. Use one currency consistently for all costs; amounts are displayed without a currency symbol.</p><button id="export">Download backup</button> <button id="restore">Restore backup</button><input type="file" id="backup-file" accept="application/json,.json" hidden><p>Restoring replaces your entire current plan and history. Save a backup first.</p><p><a href="START-HERE.html" target="_blank" rel="noopener">Open the printable START HERE guide</a></p></article>`;$('#export').onclick=exportBackup;$('#restore').onclick=()=>$('#backup-file').click();$('#backup-file').onchange=restore;return}
if(view==='history'){content.innerHTML=`<div class="section-head"><div><h2>What you have taken care of</h2><p>${state.history.length} completed maintenance records</p></div></div>`+(state.history.length?state.history.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(h=>`<article class="card"><div><span class="badge">${esc(h.category)}</span><h3>${esc(h.name)}</h3><p>${fmt(h.date)} · ${money(h.cost)}</p>${h.note?`<p class="note">${esc(h.note)}</p>`:''}</div><span class="badge">Completed</span></article>`).join(''):`<div class="empty"><h3>Every little effort counts</h3><p>When you mark a task as done, its date, cost and note are saved here.</p></div>`);return}
let tasks=state.tasks.filter(t=>view==='all'||(t.next&&t.next<=limit)).sort((a,b)=>(a.next||'9999').localeCompare(b.next||'9999'));content.innerHTML=`<div class="section-head"><div><h2>${view==='all'?'Your home maintenance':'What needs doing soon'}</h2><p>${view==='all'?`${state.tasks.length} tasks in your plan`:'Overdue tasks and the next 30 days'}</p></div><button id="presets">Choose starter tasks</button></div>`+(tasks.length?tasks.map(t=>`<article class="card"><div><span class="badge">${esc(t.category)}</span> <span class="badge ${t.next&&t.next<now?'late':t.next&&t.next<=limit?'due':''}">${t.next&&t.next<now?'Overdue · ':''}${fmt(t.next)}</span><h3>${esc(t.name)}</h3><p class="secondary">Last completed: ${t.last?fmt(t.last):'Not recorded'} · ${money(t.cost)}${t.interval?` · Every ${t.interval} ${t.unit==='days'?'day(s)':t.unit==='years'?'year(s)':'month(s)'}`:''}</p>${t.note?`<p class="note">${esc(t.note)}</p>`:''}</div><div class="card-actions"><button class="primary" data-done="${esc(t.id)}">✓ Done</button><button data-edit="${esc(t.id)}">Edit</button><button class="danger" data-delete="${esc(t.id)}" aria-label="Delete ${esc(t.name)}">Delete</button></div></article>`).join(''):`<div class="empty"><h3>${state.tasks.length?'You are on track':'Give your home a plan'}</h3><p>${state.tasks.length?'No tasks are due within 30 days. Find your full plan under All tasks.':'Start with your own tasks or choose some common maintenance tasks.'}</p><button class="primary" id="empty-action">${state.tasks.length?'View all tasks':'Choose starter tasks'}</button></div>`);$('#presets').onclick=openTemplates;const empty=$('#empty-action');if(empty)empty.onclick=()=>{if(state.tasks.length){view='all';render()}else openTemplates()};content.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));content.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>openComplete(b.dataset.done));content.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this task? Completed history will be kept.'))transaction(s=>s.tasks=s.tasks.filter(t=>t.id!==b.dataset.delete))});}
function openEditor(id){const f=$('#task-form');f.reset();$('#form-error').textContent='';const t=state.tasks.find(t=>t.id===id);f.elements.id.value=id||'';$('#form-title').textContent=t?'Edit maintenance task':'New maintenance task';if(t)Object.keys(t).forEach(k=>{if(f.elements[k])f.elements[k].value=t[k]||''});$('#editor').showModal()}
$('#task-form').onsubmit=e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f)),t={...d,id:d.id||crypto.randomUUID(),name:d.name.trim(),cost:Number(d.cost),interval:Number(d.interval)};if(!C.validateTask(t)){ $('#form-error').textContent='Check the name, dates, interval and cost.';return}if(t.last&&t.last>C.today()){$('#form-error').textContent='The last completed date cannot be in the future.';return}if(!t.next&&!t.interval){$('#form-error').textContent='Enter a next due date or a repeat interval.';return}if(!t.next)t.next=C.advance(t.last||C.today(),t.interval,t.unit);if(t.last&&t.next<=t.last){$('#form-error').textContent='The next due date must be after the last completed date.';return}if(transaction(s=>{const i=s.tasks.findIndex(x=>x.id===t.id);if(i<0)s.tasks.push(t);else s.tasks[i]=t})){$('#editor').close();toast('Task saved.')}};
function openComplete(id){completeId=id;const t=state.tasks.find(t=>t.id===id),f=$('#complete-form');f.reset();f.elements.date.value=C.today();f.elements.cost.value=t.cost;$('#complete-name').textContent=t.name;$('#complete-error').textContent='';$('#manual-next').hidden=!!t.interval;$('#complete-hint').textContent=t.interval?'The next due date is calculated from the completed date using your chosen interval.':'Without a new date, the task is finished and remains under All tasks.';$('#complete').showModal()}
$('#complete-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{if(transaction(s=>C.completeTask(s,completeId,d.date,Number(d.cost),d.note,d.next))){$('#complete').close();toast('Completed maintenance saved.')}}catch(err){$('#complete-error').textContent=err.message}};
const templates=[['Clean the range hood grease filter','Kitchen & appliances',1,'months','Check the manufacturer’s cleaning instructions.'],['Clean the dishwasher filter','Kitchen & appliances',1,'months','Follow the appliance instructions.'],['Check ventilation filters','Heating & ventilation',3,'months','Replace and clean according to the system manual.'],['Check heat pump filters','Heating & ventilation',1,'months','Adjust for your model and usage.'],['Check gutters','Roof & exterior',6,'months','Check from ground level where possible. Hire a professional for work at height.'],['Inspect the roof and exterior','Roof & exterior',12,'months','Visual inspection from ground level.'],['Clean the floor drain','Plumbing & bathroom',3,'months','Follow the drain manufacturer’s instructions.'],['Check for visible water leaks','Plumbing & bathroom',3,'months','Look under sinks and around visible connections.'],['Test smoke alarms','Safety',1,'months','Test according to the product instructions.'],['Inspect the patio and outdoor furniture','Garden & patio',12,'months','Adjust for materials, climate and season.']];
function openTemplates(){$('#template-list').innerHTML=templates.map((t,i)=>{const exists=state.tasks.some(x=>x.name===t[0]);return `<label class="template"><input type="checkbox" value="${i}" ${exists?'disabled':''}><span>${esc(t[0])}<small>${exists?'Already in your plan':`Suggested: every ${t[2]} month(s)`} · ${esc(t[1])}</small></span></label>`}).join('');$('#templates').showModal()}
$('#import-templates').onclick=()=>{const chosen=[...document.querySelectorAll('#template-list input:checked')].map(x=>templates[+x.value]);if(!chosen.length){toast('Choose at least one task.');return}if(transaction(s=>chosen.forEach(t=>s.tasks.push({id:crypto.randomUUID(),name:t[0],category:t[1],interval:t[2],unit:t[3],last:'',next:C.advance(C.today(),t[2],t[3]),cost:0,note:t[4]})))){$('#templates').close();toast(`${chosen.length} tasks imported.`)}};
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`sweforms-backup-${C.today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function restore(e){const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error();const data=JSON.parse(await file.text());if(!C.validateState(data))throw Error();if(confirm('Replace all current tasks and history with this backup?')){storageBlocked=false;if(save(data))toast('Backup restored.')}}catch{toast('This is not a valid SweForms backup.')}e.target.value=''}
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#add').onclick=()=>openEditor();$('#backup-link').onclick=()=>{view='help';render()};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false});$('#install').onclick=async()=>{await installPrompt.prompt();$('#install').hidden=true;installPrompt=null};window.addEventListener('appinstalled',()=>$('#install').hidden=true);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>toast('Offline mode could not be enabled. The app still works online.'));render();if(storageBlocked)toast('Saved data could not be read. It has not been overwritten. Open Guide & backup.');

