(function(root){
const KEY='sweforms.home.v1';
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function validDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00');return !isNaN(d)&&d.getFullYear()===+s.slice(0,4)&&d.getMonth()+1===+s.slice(5,7)&&d.getDate()===+s.slice(8,10)}
function advance(s,n,u){const d=new Date(s+'T12:00:00');if(u==='days')d.setDate(d.getDate()+n);else{const day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n*(u==='years'?12:1));const max=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,max))}return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function validateTask(t){return t&&typeof t.id==='string'&&typeof t.name==='string'&&t.name.trim().length>0&&t.name.length<=120&&typeof t.category==='string'&&typeof t.note==='string'&&t.note.length<=3000&&(!t.last||validDate(t.last))&&(!t.next||validDate(t.next))&&Number.isFinite(t.cost)&&t.cost>=0&&t.cost<=1e8&&Number.isInteger(t.interval)&&t.interval>=0&&t.interval<=1200&&['days','months','years'].includes(t.unit)}
function validateState(s){return s&&s.version===1&&Array.isArray(s.tasks)&&Array.isArray(s.history)&&s.tasks.every(validateTask)&&new Set(s.tasks.map(t=>t.id)).size===s.tasks.length&&s.history.every(h=>h&&typeof h.id==='string'&&typeof h.taskId==='string'&&typeof h.name==='string'&&validDate(h.date)&&Number.isFinite(h.cost)&&h.cost>=0&&typeof h.note==='string')}
function completeTask(state,id,date,cost,note,next){if(!validDate(date)||date>today())throw Error('Choose a valid date that is not in the future.');const t=state.tasks.find(t=>t.id===id);if(!t)throw Error('Task not found.');if(t.last&&date<t.last)throw Error('The date cannot be earlier than the last completed maintenance.');if(!Number.isFinite(cost)||cost<0)throw Error('Enter a valid cost.');if(next&&(!validDate(next)||next<=date))throw Error('The next due date must be after the completed date.');state.history.unshift({id:crypto.randomUUID(),taskId:id,name:t.name,category:t.category,date,cost,note});t.last=date;t.next=t.interval?advance(date,t.interval,t.unit):next||'';return state}
const api={KEY,today,advance,validDate,validateTask,validateState,completeTask};root.Sweforms=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
